services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'Asia/Seoul'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - ./db/pgvector_data:/var/lib/postgresql/data