services:
  semantic-image-search-pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: 'Asia/Seoul'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ../db/pgvector_data:/var/lib/postgresql/data