name: deploy
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: deploy to NCP App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.REMOTE_IP}}
          username: ${{secrets.SSH_ID}}
          password: ${{secrets.REMOTE_SSH_KEY}}
          port: ${{secrets.REMOTE_SSH_PORT}}
          script: |
            cd semantic-image-search
            run ./deploy.sh
            
      
      

  
