name: deploy
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        working-directory: semantic-image-search-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        working-directory: semantic-image-search-frontend
        run: npm install
  
      - name: Build Frontend
        working-directory: semantic-image-search-frontend
        run: npm run build
          
      - name: deploy to NCP App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.REMOTE_IP}}
          username: ${{secrets.SSH_ID}}
          password: ${{secrets.REMOTE_SSH_KEY}}
          port: ${{secrets.REMOTE_SSH_PORT}}
          script: |
            cd semantic-image-search
            ./deploy.sh
            
      
      

  
