name: deploy
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.10.11'
      
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Update npm to latest version
        run: npm install -g npm@10.8.2

      - name: npm i sharp
        run: npm i sharp
          
      - name: deploy to NCP App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_IP}}
          username: ${{secrets.SSH_ID}}
          password: ${{secrets.REMOTE_SSH_KEY}}
          port: ${{secrets.REMOTE_SSH_PORT}}
          script: |
            cd semantic-image-search
            ./deploy.sh
            
      
      

  
